### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by joeyates** [timoschilling/sun-times#1]
Hello, I'm the original author of this library and have just received a pull request (https://github.com/joeyates/ruby-sun-times/pull/3).
It'd be nice to bring the forks together. What are your thoughts?

**Comment by timoschilling** [comment]
Hello @joeyates,

nice to hear you.

Yes, we can do that, but do you kown the main reasen for the fork and the own gem?
The main Problem with you gem is that the gem name and the lib file hasn't the same name, so you need to expicit require the lib and can't use the Bundle auto require.

I will continue my gem name, for better integration.

We can do 2 thinks. First we merge our work and continue the development under the `sun-times` gem. Second you fork my stuff back or i give you a Pullrequest back.

**Comment by joeyates** [comment]
Hello @timoschilling,

I would like to continue to maintain the gem, and include your improvements, especially the name change. To do so, you would have to add me as an author of the gem with the `gem owner` command (http://guides.rubygems.org/command-reference/#gem_owner).

Would that be OK with you?

**Comment by timoschilling** [comment]
@joeyates we can do that, want we continue the development with my repo? I will add you as contributor.

**Comment by joeyates** [comment]
@timoschilling I was intending to continue development in the original repo. Would it not be better if I added you as a contributor to my repo?

**Comment by timoschilling** [comment]
@joeyates no thanks! I think I continue my own work, if you want, join me...

**Comment by joeyates** [comment]
@timoschilling I'm rather disappointed by your reaction.

I'm sure you know that normal GitHub etiquette requires that you should fork another person's project, make improvements and send a pull request.

Is there any specific reason why you think a separate permanent fork is required?

**Comment by timoschilling** [comment]
@joeyates you want, my gem, my code, but not my repo. I think it's not ok for me.

I respect the GitHub etiquette and give you a pull request!

**Comment by joeyates** [comment]
@timoschilling I see that this is not going to be resolved amicably.

You say 'my gem, my code'. Let me remind you that the original gem and original code are mine.

It would have been polite to suggest the name change for the gem in a pull request, but you did not do that. I had already published the gem and could have simply re-published under the new name. You made that impossible by publishing the modified gem under the new, improved name, without asking me if that was OK. Do you think that was the right thing to do?

The world of open source works best if people are nice. In the future, when you fork other people's repos, please try to follow normal procedure.

In order to avoid confusion, I intend stop developing the original gem and point people to your repo. OK?
